### ISSUE TITLE
Import error - Django 3.0.1 - ImportError: cannot import name 'available_attrs' from 'django.utils.decorators'

### ISSUE THREAD

**Issue by SulanthaM** [chibisov/drf-extensions#280]
Hi, I am using drf-extensions 0.5.0 with Django 3.0.1 and Python 3.7.
However, when I try to use the package, I get this error. I believe this has something to do with compatibility if Django 3.0. 

Is this an easy fix? 

```
File "/sam/Service/venv/lib/python3.7/site-packages/rest_framework_extensions/cache/decorators.py", line 4, in <module>
    from django.utils.decorators import available_attrs
ImportError: cannot import name 'available_attrs' from 'django.utils.decorators' (/sam/Service/venv/lib/python3.7/site-packages/django/utils/decorators.py)


```

**Comment by SulanthaM** [comment]
I believe that this is due to the fact the pypi repo is not properly updated. The tar and whl files still contain the bugs fixed in #276

**Comment by germainBelacel** [comment]
Any Idea, when the pypi repo will be update with a new release?

**Comment by auvipy** [comment]
will push a new pypi release soon

**Comment by OskarPersson** [comment]
@auvipy Any issue you see as a must to be fixed before release?

**Comment by auvipy** [comment]
check your email

**Comment by brianhelba** [comment]
@auvipy Can this issue be closed?

**Comment by SulanthaM** [comment]
Yes. I think this is resolved in the updated version.

**Comment by auvipy** [comment]
thanks

**Comment by joseph-vedadi** [comment]
I still face the same issue 

```py 
  from drf_yasg.views import get_schema_view
  File ".venv/lib/python3.7/site-packages/drf_yasg/views.py", line 5, in <module>
    from django.utils.decorators import available_attrs
ImportError: cannot import name 'available_attrs' from 'django.utils.decorators'

**Comment by fatogun** [comment]
File "/app/.heroku/python/lib/python3.9/site-packages/drf_yasg/views.py", line 5, in <module>
    from django.utils.decorators import available_attrs
ImportError: cannot import name 'available_attrs' from 'django.utils.decorators' (/app/.heroku/python/lib/python3.9/site-packages/django/utils/decorators.py)

**Comment by auvipy** [comment]
> File "/app/.heroku/python/lib/python3.9/site-packages/drf_yasg/views.py", line 5, in
> from django.utils.decorators import available_attrs

not related to this package
